# Generated by Django 5.0.8 on 2024-08-15 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('imagem', models.ImageField(blank=True, upload_to='empresas')),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('startup', 'StartUp'), ('pequenamedia', 'Pequena/Média Empresa'), ('grande', 'Grande Empresa')], default=(), max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descricao', models.TextField()),
                ('experiencia', models.CharField(choices=[('junior', 'Júnior'), ('pleno', 'Pleno'), ('senior', 'Sênior')], default=(), max_length=6)),
                ('contrato', models.CharField(choices=[('clt', 'CLT'), ('pj', 'PJ'), ('estagio', 'Estágio')], default=(), max_length=7)),
                ('valido_ate', models.DateField()),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('atualizado_em', models.DateField(auto_now=True)),
                ('is_ativo', models.BooleanField(default=True)),
                ('candidaturas', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.empresa')),
                ('local', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vagas.local')),
                ('stack', models.ManyToManyField(blank=True, to='vagas.stack', verbose_name='Stacks')),
            ],
        ),
    ]
