# Generated by Django 5.0.8 on 2024-08-07 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('salario', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
                ('local', models.CharField(max_length=30)),
                ('valido_ate', models.DateField()),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('atualizado_em', models.DateField(auto_now=True)),
                ('is_ativo', models.BooleanField(default=True)),
                ('n_aplicacoes', models.PositiveIntegerField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.empresa')),
            ],
        ),
    ]
