# Generated by Django 5.0.8 on 2024-08-14 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='n_aplicacoes',
        ),
        migrations.AddField(
            model_name='empresa',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='empresas'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo',
            field=models.CharField(choices=[('startup', 'Start Up'), ('pequenamedia', 'Pequena/Média Empresa'), ('grande', 'Grande Empresa')], default=(), max_length=20),
        ),
        migrations.AddField(
            model_name='vaga',
            name='candidaturas',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaga',
            name='experiencia',
            field=models.CharField(choices=[('junior', 'Júnior'), ('pleno', 'Pleno'), ('senior', 'Sênior')], default=(), max_length=6),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='local',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vagas.local'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='stack',
            field=models.ManyToManyField(blank=True, to='vagas.stack', verbose_name='Stacks'),
        ),
    ]
