# Generated by Django 5.0.8 on 2024-08-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contrato',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='stack',
        ),
        migrations.DeleteModel(
            name='Stack',
        ),
        migrations.AddField(
            model_name='vaga',
            name='stack',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('csharp', 'C#')], default=(), max_length=10),
        ),
    ]
