# Generated by Django 5.0.8 on 2024-08-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_local_stack_remove_vaga_n_aplicacoes_empresa_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='tipo',
            field=models.CharField(choices=[('startup', 'StartUp'), ('pequenamedia', 'Pequena/Média Empresa'), ('grande', 'Grande Empresa')], default=(), max_length=20),
        ),
    ]
