# Generated by Django 5.0.8 on 2024-08-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_delete_contrato_remove_vaga_stack_delete_stack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='stack',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('csharp', 'C#'), ('cplus', 'C++')], default=(), max_length=10),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='valido_ate',
            field=models.DateTimeField(),
        ),
    ]
