# Generated by Django 5.0.8 on 2024-08-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0003_alter_vaga_candidaturas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='n_aplicacoes',
        ),
    ]
