# Generated by Django 5.0.8 on 2024-08-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0004_etapa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='nome',
            new_name='cidade',
        ),
        migrations.AddField(
            model_name='local',
            name='estado',
            field=models.CharField(default='RN', max_length=2),
            preserve_default=False,
        ),
    ]
