# Generated by Django 5.0.8 on 2024-08-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0004_remove_vaga_n_aplicacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='empresas'),
        ),
    ]
