# Generated by Django 5.0.8 on 2024-08-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0005_empresa_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='vaga',
            name='tags',
            field=models.ManyToManyField(blank=True, to='vagas.tags', verbose_name='tags'),
        ),
    ]
