# Generated by Django 5.0.8 on 2024-08-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0006_tags_vaga_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
