# Generated by Django 5.0.8 on 2024-08-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0007_rename_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
