# Generated by Django 5.0.8 on 2024-08-20 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0007_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=50)),
                ('data_nascimento', models.DateField(blank=True)),
                ('sobre_mim', models.TextField(blank=True)),
                ('formacao', models.CharField(blank=True, choices=[(1, 'Ensino Fundamental Incompleto'), (2, 'Ensino Fundamental Completo'), (3, 'Ensino Médio Incompleto'), (4, 'Ensino Médio Completo'), (5, 'Ensino Médio Técnico Incompleto'), (6, 'Ensino Médio Técnico Completo'), (7, 'Ensino Superior Incompleto'), (8, 'Ensino Superior Completo')], max_length=22)),
                ('habilidades', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
